name: data_visualization
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - altair
    - pandas
    - vega
    - vega-datasets
    - jupyter
    - pyarrow
    - fastparquet
    - geopandas
    - mnist
    - shapely==2.0.1
    - plotly==5.9.0
    - ipyleaflet==0.17.4
    - ipywidgets==8.1.2
    - IPython==8.20.0